import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Placeholder Firebase configuration.
///
/// Replace the values for each platform with the settings generated by
/// `flutterfire configure` before shipping or testing against a real backend.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCejnQZN2TjMNK90iju-6VcAupSvrs_3oU',
    appId: '1:640493088075:web:365607890467bc7b304cce',
    messagingSenderId: '640493088075',
    projectId: 'cryptic-notes-b93eb',
    authDomain: 'cryptic-notes-b93eb.firebaseapp.com',
    storageBucket: 'cryptic-notes-b93eb.firebasestorage.app',
    measurementId: 'G-YQ6VXJXQEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBG_EosazJw6ZqtlImvYJgmYrTsRJVjj4',
    appId: '1:640493088075:android:9df562d891ddf3a4304cce',
    messagingSenderId: '640493088075',
    projectId: 'cryptic-notes-b93eb',
    storageBucket: 'cryptic-notes-b93eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABx0KvVaC9pOAkE-VIw08sA7tZePEXhnc',
    appId: '1:640493088075:ios:918df52f9e741228304cce',
    messagingSenderId: '640493088075',
    projectId: 'cryptic-notes-b93eb',
    storageBucket: 'cryptic-notes-b93eb.firebasestorage.app',
    iosBundleId: 'com.example.crypticNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABx0KvVaC9pOAkE-VIw08sA7tZePEXhnc',
    appId: '1:640493088075:ios:918df52f9e741228304cce',
    messagingSenderId: '640493088075',
    projectId: 'cryptic-notes-b93eb',
    storageBucket: 'cryptic-notes-b93eb.firebasestorage.app',
    iosBundleId: 'com.example.crypticNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCejnQZN2TjMNK90iju-6VcAupSvrs_3oU',
    appId: '1:640493088075:web:a6e99c154829ce9f304cce',
    messagingSenderId: '640493088075',
    projectId: 'cryptic-notes-b93eb',
    authDomain: 'cryptic-notes-b93eb.firebaseapp.com',
    storageBucket: 'cryptic-notes-b93eb.firebasestorage.app',
    measurementId: 'G-KK09V4RGLQ',
  );
}
